php:
  image: php:fpm-alpine
  volumes:
    - "./public:/var/www/html"
    - "./vendor:/var/www/vendor"
    - "./src:/var/www/src"
    - "./templates:/var/www/templates"

nginx:
  image: webdevops/nginx
  volumes:
    - "./public:/var/www/html"
  links:
    - "php"
  ports:
    - 80:80
    - 443:443
  environment:
    - WEB_PHP_SOCKET=php:9000
    - WEB_DOCUMENT_ROOT=/var/www/html
